'use client';

import './globals.css';
import { Inter } from 'next/font/google';
import Providers from '@/redux/provider';
import NavBarTop from '../components/NavBarTop/NavBarTop';
import NavBarFooter from '../components/navBarFooter/NavBarFooter';
import { Josefin_Sans } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });
import { usePathname } from 'next/navigation';

export const josefin = Josefin_Sans({
	subsets: ['latin'],
	weight: ['400', '600'],
	variable: '--font-josefin-sans',
});

// export const metadata = {

const metadata = {
	title: 'Go-Trip',
	description: 'Generated by henryTeam#14',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const pathname = usePathname();
	// console.log('Ruta actual:', pathname); //Check Ruta actual

	const renderNavBarTop = pathname !== '/register' && pathname !== '/login';
	const renderNavBarFooter = pathname !== '/register' && pathname !== '/login';

	return (
		<html lang='en'>
			<Providers>
				<body className={`${inter.className}`}>
					{renderNavBarTop && <NavBarTop />}
					{children}
					{renderNavBarFooter && <NavBarFooter />}
				</body>
			</Providers>
		</html>
	);
}
